<?php
/**
 * SAAI Admin Plugin Name class file.
 *
 * @package SAAI
 * @since 1.0.0
 */

namespace SAAI\Admin;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Admin Plugin Class
 */
class SAAI_Admin_SAAI_Blocks {

	/**
	 * Page hook for the blocks settings subpage.
	 *
	 * @var string|false
	 */
	private $blocks_settings_page_hook;

	/**
	 * Admin menu slug.
	 *
	 * @var string
	 */
	private $menu_slug;

	/**
	 * Admin submenu slug.
	 *
	 * @var string
	 */
	private $sub_menu_slug;

	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 */
	public function __construct() {
		$this->menu_slug     = 'saai-overview';
		$this->sub_menu_slug = 'saai-blocks-settings';
		add_action( 'admin_enqueue_scripts', array( $this, 'saai_admin_blocks_register_scripts' ) );
		add_filter( 'admin_body_class', array( $this, 'add_saai_admin_blocks_body_class' ) );
		add_action( 'admin_menu', array( $this, 'register_saai_admin_blocks_page' ) );
	}

	/**
	 * Instance of this class.
	 *
	 * @var SAAI_Admin_SAAI_Blocks
	 */
	private static $instance;

	/**
	 * Get the instance of this class.
	 *
	 * @return SAAI_Admin_SAAI_Blocks
	 */
	public static function instance() {
		if ( ! isset( self::$instance ) ) {
			self::$instance = new self();
			self::$instance->init();
		}
		return self::$instance;
	}

	/**
	 * Initialize the plugin.
	 */
	private function init() {
		// Initialization code here.
	}

	/**
	 * Register scripts for the admin blocks page.
	 *
	 * @param string $hook_suffix The current admin page hook suffix.
	 * @since 1.0.0
	 */
	public function saai_admin_blocks_register_scripts( $hook_suffix ) {
		if ( ! $this->blocks_settings_page_hook || $hook_suffix !== $this->blocks_settings_page_hook ) {
			return;
		}

		$bs_script_path       = SAAI_BLOCKS_PATH . '/assets/build/saai/admin/blocks-settings.js';
		$bs_script_asset_path = SAAI_BLOCKS_PATH . '/assets/build/saai/admin/blocks-settings.asset.php';

		if ( ! file_exists( $bs_script_path ) ) {
			return;
		}

		$bs_script_asset = file_exists( $bs_script_asset_path )
			? require $bs_script_asset_path
			: array(
				'dependencies' => array(),
				'version'      => filemtime( $bs_script_path ),
			);

		// Enqueue overview CSS for shared admin layout styles.
		wp_enqueue_style(
			$this->sub_menu_slug,
			SAAI_BLOCKS_URL . 'assets/build/saai/admin/overview.css',
			array(),
			file_exists( SAAI_BLOCKS_PATH . '/assets/build/saai/admin/overview.css' )
				? filemtime( SAAI_BLOCKS_PATH . '/assets/build/saai/admin/overview.css' )
				: '1.0.0'
		);

		wp_enqueue_script(
			$this->sub_menu_slug,
			SAAI_BLOCKS_URL . 'assets/build/saai/admin/blocks-settings.js',
			$bs_script_asset['dependencies'],
			$bs_script_asset['version'],
			true
		);

		$this->load_inline_script_translations( 'assets/build/saai/admin/blocks-settings.js' );

		wp_enqueue_style(
			$this->sub_menu_slug,
			SAAI_BLOCKS_URL . 'assets/build/saai/admin/blocks-settings.css',
			array( 'wp-components' ),
			file_exists( SAAI_BLOCKS_PATH . '/assets/build/saai/admin/blocks-settings.css' )
				? filemtime( SAAI_BLOCKS_PATH . '/assets/build/saai/admin/blocks-settings.css' )
				: '1.0.0'
		);
	}

	/**
	 * Register the admin blocks settings subpage.
	 *
	 * @since 1.0.0
	 */
	public function register_saai_admin_blocks_page() {
		$this->blocks_settings_page_hook = add_submenu_page(
			$this->menu_slug,
			__( 'Block Settings', 'saai-blocks' ),
			__( 'Block Settings', 'saai-blocks' ),
			'manage_options',
			$this->sub_menu_slug,
			array( $this, 'saai_blocks_settings_page_callback' )
		);
	}

	/**
	 * Callback function for the blocks settings subpage.
	 *
	 * @since 1.0.0
	 */
	public function saai_blocks_settings_page_callback() {
		echo '<div class="wrap"><div id="root-blocks-settings"></div></div>';
	}

	/**
	 * Add custom body class for the blocks settings admin page.
	 *
	 * @param string $body_class Existing body classes.
	 * @return string Modified body classes.
	 * @since 1.0.0
	 */
	public function add_saai_admin_blocks_body_class( $body_class ) {
		$screen = get_current_screen();
		if ( isset( $screen->id ) && $this->blocks_settings_page_hook && $this->blocks_settings_page_hook === $screen->id ) {
			$body_class .= ' saai-admin-page';
		}
		return $body_class;
	}

	/**
	 * Load JS translations by injecting locale data inline via wp.i18n.setLocaleData().
	 *
	 * Uses the JSON file generated by `wp i18n make-json`, whose filename is
	 * i18n/{domain}-{locale}-{md5(script_relative_path)}.json — matching the
	 * path used in the .po file's #: source references.
	 *
	 * @param string $script_relative_path Script path relative to the plugin root (e.g. 'assets/build/saai/admin/blocks-settings.js').
	 * @since 1.0.0
	 */
	private function load_inline_script_translations( $script_relative_path ) {
		$locale    = determine_locale();
		$hash      = md5( $script_relative_path );
		$json_file = SAAI_BLOCKS_PATH . '/i18n/saai-blocks-' . $locale . '-' . $hash . '.json';

		if ( ! file_exists( $json_file ) ) {
			return;
		}

		$json = file_get_contents( $json_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $json ) {
			return;
		}

		$translations = json_decode( $json, true );
		if ( ! is_array( $translations ) ) {
			return;
		}

		wp_add_inline_script(
			'wp-i18n',
			'( function( domain, translations ) {' .
				'var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;' .
				'localeData[ "" ].domain = domain;' .
				'wp.i18n.setLocaleData( localeData, domain );' .
			'} )( "saai-blocks", ' . wp_json_encode( $translations ) . ' );'
		);
	}
}
